### ISSUE TITLE
Error writing to postgreSQL database during upgrade

### ISSUE THREAD

**Issue by ewallah** [Syxton/moodle-tool_coursearchiver#12]
tool_coursearchiver
Error writing to database

×Debug info: ERROR: operator does not exist: text * integer
LINE 2: SET name=$1, value=(value * 12)
^
HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts.
UPDATE mdl_config_plugins
SET name=$1, value=(value * 12)
WHERE plugin=$2 AND name=$3
[array (
0 => 'optoutmonthssetting',
1 => 'tool_coursearchiver',
2 => 'optoutyearssetting',
)]
Error code: dmlwriteexception
×Stack trace:
line 489 of /lib/dml/moodle_database.php: dml_write_exception thrown
line 242 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
line 700 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
line 92 of /admin/tool/coursearchiver/db/upgrade.php: call to pgsql_native_moodle_database->execute()
line 628 of /lib/upgradelib.php: call to xmldb_tool_coursearchiver_upgrade()
line 1850 of /lib/upgradelib.php: call to upgrade_plugins()
line 694 of /admin/index.php: call to upgrade_noncore()

**Comment by Syxton** [comment]
@ewallah I just made another commit that should fix this.  Can you test it out and make sure that it upgrades successfully now.
