### ISSUE TITLE
Missing strings

### ISSUE THREAD

**Issue by ewallah** [Syxton/moodle-tool_coursearchiver#13]
Invalid get_string() identifier: 'optoutmonthsssetting' or component 'tool_coursearchiver'. Perhaps you are missing $string['optoutmonthsssetting'] = ''; in /admin/tool/coursearchiver/lang/en/tool_coursearchiver.php?

Invalid get_string() identifier: 'optoutmonthsssetting_help' or component 'tool_coursearchiver'. Perhaps you are missing $string['optoutmonthsssetting_help'] = ''; in /admin/tool/coursearchiver/lang/en/tool_coursearchiver.php? ++

**Comment by Syxton** [comment]
@ewallah  You may try purging cache because both of those lang strings exist.

**Comment by ewallah** [comment]
optoutmonthSSSsetting is not equal to optoutmonthSSsetting

**Comment by Syxton** [comment]
@ewallah Fixed...great catch.  Thanks!
