### ISSUE TITLE
Admins to add courses to opt-out list

### ISSUE THREAD

**Issue by mwithheld** [Syxton/moodle-tool_coursearchiver#15]
Can you please create a way for Moodle admins to add courses to the opt-out list?

- In the "Manage Opt-Outs" with a way to choose the course(s) (button? dropdown? CSV id's field?)
- And in each row of the "Course Search Results": A simple link e.g. /admin/tool/coursearchiver/optout.php?courseid=12345&userid=9876

**Comment by Syxton** [comment]
@mwithheld Check the latest commit.  I've added Opt out as a separate function of the tool.
