### ISSUE TITLE
Message_sent::create_from_ids() needs a $courseid to be passed

### ISSUE THREAD

**Issue by ocimjr** [Syxton/moodle-tool_coursearchiver#23]
moodle version : 3.4.5 (Build : 20180910)
Plugin version : 3.6.1 (Build: 2016090200) - 2018101700
How to reproduce : 
      1 - Search course on  admin/tool/coursearchiver/index.php
        2 - Select course on /admin/tool/coursearchiver/step3.php and clicked send email
        3 - On /admin/tool/coursearchiver/step3.php, select user email to send and clicked "Send 'Course to be hidden' Emails"
        4 - On page admin/tool/coursearchiver/step4.php clicked on continue
        5 - After on page admin/tool/coursearchiver/step4.php message appears

**Comment by Syxton** [comment]
@ocimjr 
Fixed in 8db4e9e
Please check and confirm.

**Comment by ocimjr** [comment]
I can confirm, it is solved.
Thank you

**Comment by Syxton** [comment]
@ocimjr Thank you for both bug reports!
