### ISSUE TITLE
Add option to include courses from subcategories

### ISSUE THREAD

**Issue by serlachner** [Syxton/moodle-tool_coursearchiver#25]
Right now, when you filter by category it will only show all courses that are directly in that category and no subcategories, which is fine. Maybe you could add a checkbox to also include all courses that are located in all subcategories of the selected category.

**Example**
Following categories are present:
SpringTerm
SpringTerm/Informatics
SpringTerm/Informatics/Security
FallTerm

In the seach form "SpringTerm" is selected as category.

**Option 1 (without subcategories, current behaviour):**
Only courses directly in the category "SpringTerm" are returned.

**Option 2 (include subcategories):**
Courses in the categories "SpringTerm", "SpringTerm/Informatics" and "SpringTerm/Informatics/Security" are returned.

**Comment by Syxton** [comment]
@serlachner Check out the latest commit.  Hope it works as expected.

**Comment by serlachner** [comment]
That was quick, amazing. Tested it and works exactly as expected. 👍
Thank you very much!
Cheers

--> CLOSED
