### ISSUE TITLE
Exception - RecursiveDirectoryIterator::__construct([dataroot]/CourseArchives): failed to open dir: No such file or directory

### ISSUE THREAD

**Issue by jeffw87** [Syxton/moodle-tool_coursearchiver#26]
Release 3.7.1 (Build: 2016090200) (2018121304)

Issue with installing on Moodle 3.6.2 & 3.6.1 with this error message: 

!!! Exception - RecursiveDirectoryIterator::__construct([dataroot]/CourseArchives): failed to open dir: No such file or directory !!!
!! 
Error code: generalexceptionmessage !!
!! Stack trace: * line 148 of /admin/tool/coursearchiver/db/upgrade.php: UnexpectedValueException thrown
* line 148 of /admin/tool/coursearchiver/db/upgrade.php: call to RecursiveDirectoryIterator-&gt;__construct()
* line 636 of /lib/upgradelib.php: call to xmldb_tool_coursearchiver_upgrade()
* line 1852 of /lib/upgradelib.php: call to upgrade_plugins()
* line 186 of /admin/cli/upgrade.php: call to upgrade_noncore()

**Comment by Syxton** [comment]
I have seen a few issues like this, but in all cases it was a network mount in linux that wasn't given the proper permissions.  Can you give some more info on the environment?

**Comment by Syxton** [comment]
Also, what version of the archiver are you updating from?

**Comment by jeffw87** [comment]
Hi coursearchive version: Release 3.7.1 (Build: 2016090200) (2018121304).
Our moodle folder is not writable to apache and our moodledata is writable for apache. None of our other plugins are acting up with this. I did have the plugin working fine with your 3.5 release but it is only failing for this release.

**Comment by Syxton** [comment]
@jeffw87  This version of the plugin does an update process where it indexes any files that exist in the archive directory.  The update process is not trying to write to the folder at the time of upgrade, it is just recursively scanning it for files and subfolders.   Does the CourseArchives folder exist in the dataroot directory?

**Comment by jeffw87** [comment]
moodledata does not have the coursearchive folder.

**Comment by Syxton** [comment]
Ok, this would be the issue.  While it is possible to use many functions of the plugin without the folder, the archiving process would create the folder.  Or you can simply create the CourseArchives folder in the moodledata folder and run the update.  You can remove the folder afterword if you wish.  I will make an update to work around the possibility of an upgrade on a site that hasn't got the archive folder created yet.

**Comment by Syxton** [comment]
@jeffw87 I just pushed a fix to db/upgrade.php that should fix this issue for you.

**Comment by jeffw87** [comment]
Thank you Syxton. Excellent customer service :).
I grabbed a copy from github but it looks like we need to change the version for moodle to trigger an upgrade. Do you need further testing before pushing it to moodle.org?

**Comment by Syxton** [comment]
Thank you for the report.  Closing.
