### ISSUE TITLE
Possibility to inform other roles

### ISSUE THREAD

**Issue by KerstinSc** [Syxton/moodle-tool_coursearchiver#27]
It would be great to have an option for setting the roles which should be considered as teachers. At the moment it's the default "editingteacher". Many installations work with individual roles and thus the search results in "nobody to inform". 

Thank you!

**Comment by Syxton** [comment]
@KerstinSc Thank you for the input.  I'll put it on my list of TODO's

**Comment by Syxton** [comment]
#51 should take this off my todo list
