### ISSUE TITLE
Option to Archive but not Delete

### ISSUE THREAD

**Issue by bradnielsen2981** [Syxton/moodle-tool_coursearchiver#30]
I quite like this tool, but I would really like to be able to archive Courses into a Category called Past Courses without deleting the current courses. in other words, Year 10 Maths, becomes Past Courses > Year 10 Maths, and the current Year 10 Maths Course still exists. 

It would also be great to be able to bulk reset courses.

cheers,
Brad

**Comment by Syxton** [comment]
@bradnielsen2981 See release 4.1.4
