### ISSUE TITLE
Add course end date to search

### ISSUE THREAD

**Issue by bfriesenvcc** [Syxton/moodle-tool_coursearchiver#31]
I'd love to see the course end date added to the search page. Alternatively, or additionally, since our Course IDs are an indicator of a time period, allowing wildcards in that search field would be beneficial.

Thanks for your time!

**Comment by Syxton** [comment]
@bfriesenvcc check out the 3.7.3 version I just put out.  I believe it handles both cases.

**Comment by bfriesenvcc** [comment]
It doesn't appear to handle the wildcard situation, but I'm happy to see the end date! You're my hero!
