### ISSUE TITLE
Coding error detected, it must be fixed by a programmer: Invalid property courseid specified

### ISSUE THREAD

**Issue by MoodleMood** [Syxton/moodle-tool_coursearchiver#32]
# Course Archiver
### Sending Emails

Coding error detected, it must be fixed by a programmer: Invalid property courseid specified

**Debug info:** 
Error code: codingerror

**Stack trace:**
line 215 of /lib/classes/message/message.php: coding_exception thrown
line 824 of /admin/tool/coursearchiver/classes/processor.php: call to core\message\message->__set()
line 350 of /admin/tool/coursearchiver/classes/processor.php: call to tool_coursearchiver_processor->sendemail()
line 100 of /admin/tool/coursearchiver/step4.php: call to tool_coursearchiver_processor->execute()

## System information:

**Moodle:**
Release: 3.1.18
Build: 20190513

**Plugin:**
Release: 3.7.3 
Build: 2016090200
(2019062700)

__________________________________________________________

_Note:_

The same issue with the previous version of the plugin:

Release: 3.7.2 
Build: 2016090200
(2018121306)

**Updating the plugin to the latest version hasn't resolved the issue.**

For further details see the attached screenshots, please.

![Pic_01](https://user-images.githubusercontent.com/54653712/63907136-63bc2a00-ca6e-11e9-8626-67033eba0f74.jpg)

![Pic_02](https://user-images.githubusercontent.com/54653712/63907138-6880de00-ca6e-11e9-9eaa-315bf016048e.jpg)

![Pic_03](https://user-images.githubusercontent.com/54653712/63907142-6cacfb80-ca6e-11e9-9928-bd267ffb8955.jpg)

![Pic_04](https://user-images.githubusercontent.com/54653712/63907145-7171af80-ca6e-11e9-8126-cdf79dfb1e84.jpg)

![Pic_05](https://user-images.githubusercontent.com/54653712/63907147-77679080-ca6e-11e9-823c-78ff2f6579cc.jpg)

![Pic_06](https://user-images.githubusercontent.com/54653712/63907152-7afb1780-ca6e-11e9-82b7-459e1fd58f60.jpg)

![Pic_07](https://user-images.githubusercontent.com/54653712/63907155-7e8e9e80-ca6e-11e9-97c2-2652e8e69741.jpg)

**Comment by Syxton** [comment]
@MoodleMood Please update with the latest version (currently only available from github). Includes a fix.
