### ISSUE TITLE
Activity archived/restore

### ISSUE THREAD

**Issue by bohnmd** [Syxton/moodle-tool_coursearchiver#33]
Are the activities included with the Archive?  I just started trialing the plugin and can not find a way to restore a full course; only the shell is restored.

If a course has content, let's say three activities, does the Archive process not save those activities?  Then, does the archive>restore feature not allow those activities to be restored?

Note:  We are looking for an option to BULK backup courses at the category level.  I was hoping by archiving the category/courses that it would also include the activities/content.  I don't need the enrollment etc...just looking to save the actual course material.

If this plugin does not do these things then that is perfectly fine...doesn't advertise that it does.  Was just hoping for a solution!

p.s.  For what it IS advertised to do...it works great!

Thank you,

Mark

**Comment by Syxton** [comment]
@bohnmd The Archive process is really just a full backup followed by a deletion of the course.  Every activity, enrollment, and submission should be saved in the archived file.

**Comment by bohnmd** [comment]
> @bohnmd The Archive process is really just a full backup followed by a deletion of the course. Every activity, enrollment, and submission should be saved in the archived file.
