### ISSUE TITLE
Problems with database schema

### ISSUE THREAD

**Issue by foxlapinou** [Syxton/moodle-tool_coursearchiver#35]
Hi,

I'm using Moodle 3.7.4 and latest Course archiver version. I've checked the database schema (admin/cli/check_database_schema.php) and found errors related to Course archiver plugin :
```
tool_coursearchiver_optout
* column 'optoutlength' should be NOT NULL (I)
-------------------------------------------------------------------------------
tool_coursearchiver_archived
* column 'timetodelete' should be NOT NULL (I)
```

I suspect there's a coherence problem between files db/upgrade.php and db/install.xml. Do you think you can make something to correct this?

Or is the problem only in my Moodle installation? And if it's the case, how to correct this?

Thanks in advance if you can provide information.
Séverin

**Comment by Syxton** [comment]
Fixed in latest commit
