### ISSUE TITLE
Add abillity to exclude usernames/roles from last accessed query

### ISSUE THREAD

**Issue by haietza** [Syxton/moodle-tool_coursearchiver#38]
It would be helpful if it were possible to add usernames and/or roles that could be excluded from the query for last accessed before courses. We have site admins who may have accessed a course for reasons other than engagement, and we would still like those courses to be flagged for last accessed before searches for hiding/archiving. Currently, ANY access to a course will remove it from the last accessed before search. Thank you!

**Comment by Syxton** [comment]
@haietza if you are still interested, could you try out the following updated branch?  [](https://github.com/Syxton/moodle-tool_coursearchiver/tree/ignore_accesses)

You will find two checkboxes under the Access Before/After area of the search.

**Comment by Syxton** [comment]
https://github.com/Syxton/moodle-tool_coursearchiver/tree/ignore_accesses

**Comment by haietza** [comment]
@Syxton Yes this looks good! I was originally envisioning the ability to select specific roles whose access would be excluded, however I don't think that is actually necessary. For our purposes, the admin and site admin roles being excluded is just what we need.

I did get a couple PHP warnings with the new branch, in case you need the info:

Notice: Trying to access array offset on value of type int in /var/www/html/global-311/admin/tool/coursearchiver/classes/step1_form.php on line 187
Call Stack
#	Time	Memory	Function	Location
1	0.0004	374688	{main}( )	.../index.php:0
2	1.6812	14115976	tool_coursearchiver_step1_form->is_validated( )	.../index.php:57
3	1.6812	14115976	tool_coursearchiver_step1_form->validate_defined_fields( )	.../formslib.php:589
4	1.6880	14117880	tool_coursearchiver_step1_form->validation( )	.../formslib.php:653

Notice: Trying to access array offset on value of type int in /var/www/html/global-311/admin/tool/coursearchiver/classes/step1_form.php on line 188
Call Stack
#	Time	Memory	Function	Location
1	0.0004	374688	{main}( )	.../index.php:0
2	1.6812	14115976	tool_coursearchiver_step1_form->is_validated( )	.../index.php:57
3	1.6812	14115976	tool_coursearchiver_step1_form->validate_defined_fields( )	.../formslib.php:589
4	1.6880	14117880	tool_coursearchiver_step1_form->validation( )	.../formslib.php:653

Thanks so much!

**Comment by Syxton** [comment]
@haietza Thanks for the feedback.  I have fixed the validation issues with commit 737eb912aa4b694c839009d83a97ae145882821b

**Comment by haietza** [comment]
@Syxton Did you/are you going to get this ignore_accesses branch merged into master? I didn't see it in the commits but may have missed it. Thanks!

**Comment by Syxton** [comment]
@haietza  Thank you for the reminder.  I was actually working on cleaning up the code and making sure everything looked good for moodle 4.0.  i have included those changes here: https://github.com/Syxton/moodle-tool_coursearchiver/tree/4.0_changes
I have also pushed those changes onto master.  The only difference with the 4.0 branch so far is some codechecker and whitespace fixes.
