### ISSUE TITLE
Add ability to manage save points

### ISSUE THREAD

**Issue by haietza** [Syxton/moodle-tool_coursearchiver#39]
It would be helpful if it were possible to edit or delete save points, such that they can be removed when they are no longer needed (versus building up in the resume drop down menu) and so additional course searches could be added to existing save point results. Thank you!

**Comment by bfriesenvcc** [comment]
This is the reason I came here! I've been waiting for a way to delete save points. Our list is crazy.

**Comment by Syxton** [comment]
#45 creates a new save points management screen with the ability to remove save points
