### ISSUE TITLE
Search in subcategories doesn't work

### ISSUE THREAD

**Issue by Kemmotar83** [Syxton/moodle-tool_coursearchiver#46]
Hi @Syxton , 

this commit (https://github.com/Syxton/moodle-tool_coursearchiver/commit/a16e38413a5477d1e093b4dbee5ddbf0317b7aab) seems to have introduced a regression with search in subcategories.
When searching with "Include courses in subcategories" enabled, courses in subcategories are not included.

I've done some code digging and I found something "wrong" in function _get_courselist_ of _tool_coursearchiver_processor_ class (_processor.php_). Moving the "_$params[$truekey] = $value;_" line outside the specific conditions cause the $params["subcats"] item to be wrongly overwritten.
_$params["subcats"]_ is correctly parsed when the key is "catid" (truekey: category) [row: 1159] but, since the "subcats" key exists both in $this->data and $searchcriteria arrays, it is also considered a valid criteria at the next iteration when the key is "subcats", so _$params["subcats"]_ is immediately overwritten with the boolean "true" value from $this->data["subcats"] [row: 1135].

In my opinion, since "subcats" isn't really a "search criteria" by itself but only a specification of "category" criteria, it should be removed from the $searchcriteria array (row: 116).

What do you think?

Giorgio

**Comment by Syxton** [comment]
@Kemmotar83 Thanks for the report.  You are 100% correct, and I have committed 1c1f708 to fix it.

**Comment by Kemmotar83** [comment]
Thank you @Syxton for this quick fix.
