### ISSUE TITLE
Backups not working with '/' in course id

### ISSUE THREAD

**Issue by nomisge** [Syxton/moodle-tool_coursearchiver#49]
Backups (and thus also archiving) are failing for course with '/' in their course_id. I get following messages, depending on  configuration.

- With:  `backup_auto_storage` set to "Course backup filearea" :
  `copy([some_path].../CourseArchives/2023/2023-09-01-ID-1965-IDNUM-DKZ.FR.NW.202223.CH/9c-2022-23-Ch-9c.mbz): Failed to   open stream: No such file or directory in [path_to_moodle]/lib/filestorage/file_system_filedir.php on line 234`
  Within the Course backup filearea the backup is just named "backup.mbz" (see also #37)
  The target directory is created, but not the target file.

- With   `backup_auto_storage` set to "Specified directory for automated backups":
 `PHP Warning:  rename([autobackup path].../sicherung-moodle2-course-1965-20230904-1311-nu.mbz,[some_path].../CourseArchives/2023/2023-09-04-ID-1965-IDNUM-DKZ.FR.NW.202223.CH/9c-2022-23-Ch-9c.mbz): No such file or directory in  [path_to_moodle]/admin/tool/coursearchiver/classes/processor.php on line 665`
  The backup file `sicherung-moodle2-course-1965-20230904-1311-nu.mbz` exists and seems to be correctly named.
  The target directory is created, but not the target file.

Maybe when creating the targetfile-name the '/' character needs to be escaped or left out?

I'd appreciate any help :-). Ideally soon, since I'd like to archive everything this week, since the school year starts next week, with new courses.

**Comment by Syxton** [comment]
@nomisge in classes/processor.php around line 619 make it look like this
`            } else {
                $suffix = '-ID-'.$obj["course"]->id.'-IDNUM-'.$obj["course"]->idnumber;
                $suffix = preg_replace($matchers, '-', $suffix);
            }`

**Comment by Syxton** [comment]
@nomisge I will roll out a fix soon for courses with idnumbers with non filename safe characters.  Thanks for the report!

**Comment by Syxton** [comment]
Fixed in Release 4.1.6

**Comment by nomisge** [comment]
@Syxton This was quick work! It's working on my system. Thx.
