### ISSUE TITLE
Use of 'editingteacher' role by name as opposed to archetype

### ISSUE THREAD

**Issue by jjs105** [Syxton/moodle-tool_coursearchiver#52]
In our instance of Moodle we have renamed the 'Editing Teacher' role name and shortname to better match our user model.

This means that the DB query to identify a default value for the new 'ownerroleid' setting returns a false result which in turn results in the following warning and no default value for the new setting being configured.

Warning: Attempt to read property "id" on bool in /srv/www/admin/tool/coursearchiver/settings.php on line 55

To fix this issue we have made the query use the 'archetype' column of the role table and select only the first result (as we have multiple roles based on the editingteacher archetype).

A better approach might be to simply not set a default in the case where the query fails (although I do not know what the knock on affects of this may be). Which is the current behaviour as the warning is ignored.

It should also be noted that prior to this update the same issue/warning was likely occurring where the original hard-coded checks against the editingteacher shortname were also being used.

**Comment by Syxton** [comment]
Fixed in latest release.  Thank you for the report.
