### ISSUE TITLE
found more than one record!

### ISSUE THREAD

**Issue by haietza** [Syxton/moodle-tool_coursearchiver#54]
We have more than one role in our installation that uses the archetype 'editingteacher', so we are seeing the following error:

Error: mdb->get_record() found more than one record!

    line 1691 of /lib/dml/moodle_database.php: call to debugging()
    line 1651 of /lib/dml/moodle_database.php: call to moodle_database->get_record_sql()
    line 1630 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
    line 54 of /admin/tool/coursearchiver/settings.php: call to moodle_database->get_record()
    line 81 of /lib/classes/plugininfo/tool.php: call to include()
    line 735 of /admin/settings/plugins.php: call to core\plugininfo\tool->load_settings()
    line 8831 of /lib/adminlib.php: call to require()
    line 835 of /admin/index.php: call to admin_get_root()

Looks like line 54 of settings.php needs to use get_records and then somehow select one to be the default (maybe the first one sorted by ID since that will likely be the Moodle core role)?

**Comment by Syxton** [comment]
@haietza And here I was thinking this was an easy change. ok, I'll fix this.

**Comment by haietza** [comment]
@Syxton Haha, no good deed goes unpunished ;).

**Comment by Syxton** [comment]
ok #53 regression fixed.  It will now select ALL archetype with "editingteacher" and if none exist it will just select the first role.  If your site doesn't have any roles....I can't help you. lol.  I recreated yesterday's release to include this fix.
