### ISSUE TITLE
Course: (ID) "NAME" could not be backed up or archived.

### ISSUE THREAD

**Issue by a-tullo** [Syxton/moodle-tool_coursearchiver#60]
I cannot backup any of my courses using this plugin, I tried with debug active but I do not get any more info than the title, it could be nice knowing why it's not working, I tried with the default path and folder and I also tried messing around with other folders and path other than the default, but I can't get it working, any help is appriciated, thanks.

**Comment by Syxton** [comment]
@a-tullo can you install the version here: https://github.com/Syxton/moodle-tool_coursearchiver/tree/better_errrors and let me know if that helps?

**Comment by a-tullo** [comment]
Good day @Syxton, thanks for the swift reply.
This definitely helps.

**Comment by a-tullo** [comment]
@Syxton ehy regarding this, the talking error sure helped in expliciting that the plugin could not create the path to save the backups, but still after many tries with different permission configurations, the only thing that got the plugin working was writing "/moodledata" in "system path that archiver folders are placed in" even tho that's supposed to be the default option, maybe you want to look into that, kinda strange

**Comment by Syxton** [comment]
@a-tullo  Thank you for the feedback.  I will look into ways to improve and clarify the path settings.
