### ISSUE TITLE
Moodle 4.4.x

### ISSUE THREAD

**Issue by Kerber0ss** [Syxton/moodle-tool_coursearchiver#62]
Hello, is there a version planned for moodle 4.4 and above and when?

**Comment by Syxton** [comment]
@Kerber0ss We are currently using it on our 4.4 installation.  I will update the plugin library to note that it works in 4.4

**Comment by Kerber0ss** [comment]
> @Kerber0ss We are currently using it on our 4.4 installation. I will update the plugin library to note that it works in 4.4

Thank you!
